import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Peronio Rocket - Display</title>
        <meta
          name='description'
          content='Generated by @rainbow-me/create-rainbowkit'
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ConnectButton />

        <h1 className={styles.title}>
          Bienvenidos a <a href=''>Peronio Rocket</a>
        </h1>

        <p className={styles.description}>
          Aquí se encontrará la App Visual de la TV
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <h2>Ejemplo</h2>
            <p>De Grid.</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        Hecho con ❤️ por <b>Peronio.AR</b>
      </footer>
    </div>
  );
};

export default Home;
