import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { Launch } from "../components/Launch";
import { SkyBackground } from "../components/SkyBackground";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Peronio Rocket - Display</title>
        <meta
          name='description'
          content='Generated by @rainbow-me/create-rainbowkit'
        />
        <script
          src='//www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js'
          async
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <Launch />
      </main>

      <footer className={styles.footer}>
        Hecho con ❤️ por <b>Peronio.AR</b>
      </footer>
    </div>
  );
};

export default Home;
