import Head from "next/head";
import type { NextPage } from "next";

import { useState } from "react";

import styles from "../styles/Home.module.css";
import { LaunchScreen } from "../components/screens/LaunchScreen";
import { MainScreen } from "../components/screens/MainScreen";

enum Screen {
  LAUNCH,
  MAIN,
  MOON,
  LEADERBOARD,
}

const ROCKETGAME_CONTRACT = process.env.NEXT_PUBLIC_ROCKETGAME_CONTRACT;
console.dir(process.env);

const Home: NextPage = () => {
  const [screen, setScreen] = useState<Screen>(Screen.MAIN);

  const startLaunch = () => {
    setScreen(Screen.LAUNCH);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Peronio Rocket - Display</title>
        <meta
          name='description'
          content='Generated by @rainbow-me/create-rainbowkit'
        />
        <script
          src='//www.gstatic.com/cast/sdk/libs/caf_receiver/v3/cast_receiver_framework.js'
          async
        />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        {screen == Screen.MAIN ? (
          <MainScreen
            start={startLaunch}
            contractAddress={ROCKETGAME_CONTRACT}
          />
        ) : (
          ""
        )}
        {screen == Screen.LAUNCH ? <LaunchScreen /> : ""}
      </main>
    </div>
  );
};

export default Home;
